---
- import_tasks: install.yml
  tags:
    - install

- include_tasks: borg-server.yml
  when: inventory_hostname in groups.borgbackup_servers

- import_tasks: borg-client.yml
  when: inventory_hostname not in groups.borgbackup_servers

- import_tasks: management.yml
  tags:
    - mgmt
